### ISSUE TITLE
DARPA Submissions Require 12pt Font Size

### ISSUE THREAD

**Issue by harrison-caudill** [KarrLab/ScientificLatexClasses#1]
```
All submissions must be written in English with type not smaller
than 12-point font. A page is defined as being no larger than an
electronically formatted page of 8.5” by 11.0” with type not
smaller than 12 point.
```

https://github.com/KarrLab/latex-grant/blob/f87bba7b62aba6744313a4faf1b87057f53d539b/grant/grant.dtx#L826

**Comment by jonrkarr** [comment]
The DAPRA class already is set to 12pt Times New Roman and 8.5" x 11" paper with 1" margins. Line 826 is part of the definition of the DOE class.

**Comment by harrison-caudill** [comment]
apologies,  I was looking at the `%</grant-darpa>` ending the darpa
section rather than beginning.


On Wed, May 8, 2019 at 12:37 PM Jonathan Karr <notifications@github.com> wrote:
>
> The DAPRA class already is set to 12pt Times New Roman and 8.5" x 11" paper with 1" margins. Line 826 is part of the definition of the DOE class.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Harrison Caudill
Satellite Communications
HyperSpectral Imaging
+1 559.464.5387
harrison@hypersphere.org
